### ISSUE TITLE
Postsrsd and dynamic domains

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/stockton#48]
https://github.com/roehling/postsrsd/issues/31

I had never thought of this but I tell postsrsd what domain to use on the rewrites, but it would be way cooler if it got an email: `foo@example.com` and just used `example.com` as the email address, sadly, it doesn't look like this is possible.

**Comment by iwikus** [comment]
Hi, this feature is important for DMARC. If you setup DMARC record, it is required to have all headers "aligned" = from same domain  (or subdomain)
https://stackoverflow.com/questions/23984309/dmarc-says-spf-fail-even-with-spf-record

With Postsrsd return-path si rewritten to value in SRS_DOMAIN, which will trigger DMARC report with spf failure. 

See 3. Verify domain alignment in https://returnpath.com/downloads/authenticating-email-dmarc-spf-dkim-quick-start-guide/

Yes, it is stupid DMARC requirement :(

**Comment by Jaymon** [comment]
You're right! I spaced on the problems this would cause for DMARC since I don't use DMARC personally and Stockton isn't set up to take advantage of it, but I definitely don't want to make it harder for Stockton to implement DMARC in the future.

Thanks for the heads up!
